document.addEventListener('DOMContentLoaded', function () {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
        const url = new URL(tabs[0].url);
        const domain = url.hostname;
        document.getElementById('domainPreview').innerText = `Domain: ${domain}`;
    });
});

document.getElementById("exportJsonBtn").addEventListener("click", () => {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
        const url = new URL(tabs[0].url);
        const domain = url.hostname;

        chrome.cookies.getAll({ domain: domain }, function (cookies) {
            if(!cookies || cookies.length === 0) {
                alert(`No cookies found for ${domain}.`);
                return;
            }

            const jsonOutput = JSON.stringify(cookies, null, 2);
            const blob = new Blob([jsonOutput], { type: "application/json" });
            saveAs(blob, `cookies_${domain}.json`);
        });
    });
});

document.getElementById("exportNetscapeBtn").addEventListener("click", () => {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
        const url = new URL(tabs[0].url);
        const domain = url.hostname;

        chrome.cookies.getAll({ domain: domain }, function (cookies) {
            if(!cookies || cookies.length === 0) {
                alert(`No cookies found for ${domain}.`);
                return;
            }

            let netscapeOutput = "# Netscape HTTP Cookie File\n";
            netscapeOutput += "# https://curl.se/docs/http-cookies.html\n";
            netscapeOutput += "# This file was generated by libcurl! Edit at your own risk.\n\n";

            cookies.forEach(cookie => {
                const cookieDomain = cookie.domain.startsWith(".") ? cookie.domain.slice(1) : cookie.domain;
                netscapeOutput += `${cookieDomain}\t${cookie.hostOnly ? "TRUE" : "FALSE"}\t${cookie.path}\t${cookie.secure ? "TRUE" : "FALSE"}\t${cookie.expirationDate ? Math.floor(cookie.expirationDate) : "0"}\t${cookie.name}\t${cookie.value}\n`;
            });

            const blob = new Blob([netscapeOutput], { type: "text/plain" });
            saveAs(blob, `cookies_${domain}.txt`);
        });
    });
});

document.getElementById("exportHeaderBtn").addEventListener("click", () => {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
        const url = new URL(tabs[0].url);
        const domain = url.hostname;

        chrome.cookies.getAll({ domain: domain }, function (cookies) {
            if(!cookies || cookies.length === 0) {
                alert(`No cookies found for ${domain}.`);
                return;
            }

            const headerOutput = cookies.map(cookie => `${cookie.name}=${cookie.value}`).join("; ");
            const blob = new Blob([headerOutput], { type: "text/plain" });
            saveAs(blob, `cookies_${domain}_header.txt`);
        });
    });
});
